app:
  title: Janus
  baseUrl: ${BASE_URL}:7007

backend:
  baseUrl: ${BASE_URL}:7007
  auth:
    keys:
      - secret: "password"
  https: true
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  cors:
    origin: ${BASE_URL}:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
app:
  title: Janus IDP
  baseUrl: ${BASE_URL}

backend:
  listen: 0.0.0.0:7007
  baseUrl: ${BASE_URL}

catalog:
  locations:
    - type: file
      target: /opt/app-root/src/catalog-entities/users.yaml
      rules:
        - allow: [User, Group]
