services:
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
  janus-idp:
    command: '--config app-config.local.yaml'
    image: 'quay.io/janus-idp/backstage-showcase:next'
    ports:
      - '7007:7007'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
      - LOG_LEVEL=debug
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - './app-config.local.yaml:/opt/app-root/src/app-config.local.yaml'
      - './deploy:/opt/app-root/src/dynamic-plugins-root:Z'
    depends_on:
      db:
        condition: service_healthy