services:
  db:
    image: docker.io/library/postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    env_file: ".env"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  rhdh:
    image: "quay.io/janus-idp/backstage-showcase:next"
    env_file: ".env"
    entrypoint:
      [
        "node",
        "packages/backend",
        "--no-node-snapshot",
        "--config",
        "app-config.yaml",
        "--config",
        "app-config.example.yaml",
        "--config",
        "app-config.example.production.yaml",
        "--config",
        "app-config.local.yaml",
      ]
    ports:
      - "7007:7007"
    volumes:
      - "./app-config.local.yaml:/opt/app-root/src/app-config.local.yaml"
      - "./catalog-entities:/opt/app-root/src/catalog-entities:Z"
      - "./dynamic-plugins-root:/opt/app-root/src/dynamic-plugins-root:Z"
    environment:
      # Reference database service
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
