# Example dynamic plugin override config.
# Copy to dynamic-plugins.override.yaml to activate local plugins.

includes:
  - dynamic-plugins.default.yaml

# Below you can add custom dynamic plugins, including local ones.
plugins:
  - package: ./local-plugins/catalog-backend-module-keycloak
    disabled: false
